server:
  port: 8888

spring:
  application:
    name: gateway
  cloud:
    discovery:
      enabled: false
    gateway:
      routes:
        - id: customer-service
          uri: http://localhost:8080
          predicates:
            - Path=/customers/**
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/products/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
